package com.coralblocks.coralproto.versioning;

import java.io.IOException;

import com.coralblocks.coralproto.AbstractProto;
import com.coralblocks.coralproto.IDL;
import com.coralblocks.coralproto.field.BooleanField;
import com.coralblocks.coralproto.field.DoubleField;
import com.coralblocks.coralproto.field.LongField;
import com.coralblocks.coralproto.field.SubtypeField;
import com.coralblocks.coralproto.field.TypeField;
import com.coralblocks.coralproto.field.VarCharsField;

public class NewOrderMessage extends AbstractProto {
		
	private static final String IDL_CODE = """
			
			TYPE = N
			SUBTYPE = O
			
			symbol: varchars(64) 
			price: double
			side: boolean
			size: long
	""";
	
	public static void main(String[] args) throws IOException {
		IDL idl = new IDL(IDL_CODE, IDL.INDENT + IDL.INDENT);
		String className = NewOrderMessage.class.getSimpleName();
		String filePath = "src/test/java/com/coralblocks/coralproto/versioning/" + className + ".java";
		String sourceCode = idl.getCode();
		IDL.replaceAutoGeneratedCode(filePath, sourceCode);
	}
	
	// Auto-generated code. Do not edit or change anything below here
	
	// BEGIN_AUTO_GENERATED_CODE

        public static final char TYPE = 'N';
        public static final char SUBTYPE = 'O';

        public final TypeField typeField = new TypeField(this, TYPE);
        public final SubtypeField subtypeField = new SubtypeField(this, SUBTYPE);

        public final VarCharsField symbol = new VarCharsField(this, 64);

        public final DoubleField price = new DoubleField(this);

        public final BooleanField side = new BooleanField(this);

        public final LongField size = new LongField(this);


	// END_AUTO_GENERATED_CODE
}
