package com.coralblocks.coralproto.versioning;

import java.io.IOException;

import com.coralblocks.coralproto.AbstractProto;
import com.coralblocks.coralproto.IDL;
import com.coralblocks.coralproto.field.BooleanField;
import com.coralblocks.coralproto.field.IntField;
import com.coralblocks.coralproto.field.LongField;
import com.coralblocks.coralproto.field.SubtypeField;
import com.coralblocks.coralproto.field.TypeField;
import com.coralblocks.coralproto.field.VarCharsField;
import com.coralblocks.coralproto.field.VersionField;

public class NewOrderMessage_2 extends AbstractProto {
	
	private static final String IDL_CODE = """
			
			TYPE = N
			SUBTYPE = O
			VERSION = 2
			
			clientId: int
			symbol: varchars(64)
			symbolId: int 
			price: long
			side: boolean
			size: long
			
	""";
	
	public static void main(String[] args) throws IOException {
		IDL idl = new IDL(IDL_CODE, IDL.INDENT + IDL.INDENT);
		String className = NewOrderMessage_2.class.getSimpleName();
		String filePath = "src/test/java/com/coralblocks/coralproto/versioning/" + className + ".java";
		String sourceCode = idl.getCode();
		IDL.replaceAutoGeneratedCode(filePath, sourceCode);
	}
	
	// Auto-generated code. Do not edit or change anything below here
	
	// BEGIN_AUTO_GENERATED_CODE

        public static final char TYPE = 'N';
        public static final char SUBTYPE = 'O';
        public static final short VERSION = 2;

        public final TypeField typeField = new TypeField(this, TYPE);
        public final SubtypeField subtypeField = new SubtypeField(this, SUBTYPE);
        public final VersionField versionField = new VersionField(this, VERSION);

        public final IntField clientId = new IntField(this);

        public final VarCharsField symbol = new VarCharsField(this, 64);

        public final IntField symbolId = new IntField(this);

        public final LongField price = new LongField(this);

        public final BooleanField side = new BooleanField(this);

        public final LongField size = new LongField(this);


	// END_AUTO_GENERATED_CODE
}
