package com.coralblocks.coralproto;

import java.io.IOException;

import org.junit.Assert;
import org.junit.Test;

import com.coralblocks.coralproto.field.BytesField;
import com.coralblocks.coralproto.field.CharsField;
import com.coralblocks.coralproto.field.SubtypeField;
import com.coralblocks.coralproto.field.TypeField;
import com.coralblocks.coralproto.field.VarBytesField;
import com.coralblocks.coralproto.field.VarCharsField;


public class CharsAndBytesTest {
	
	public static class CharsAndBytesProtoMessage extends AbstractProto {
		
		private static final String IDL_CODE = """
				
				TYPE = C
				SUBTYPE = B
				
				myChars: chars(128) 
				myVarChars: varchars(1024)
				myBytes: bytes(128) 
				myVarBytes: varbytes(1024)				
				
		""";
		
		public static void main(String[] args) throws IOException {
			IDL idl = new IDL(IDL_CODE, IDL.INDENT + IDL.INDENT);
			String filePath = "src/test/java/com/coralblocks/coralproto/" + CharsAndBytesTest.class.getSimpleName() + ".java";
			String sourceCode = idl.getCode();
			IDL.replaceAutoGeneratedCode(filePath, sourceCode);
		}
		
		// Auto-generated code. Do not edit or change anything below here
		
		// BEGIN_AUTO_GENERATED_CODE

        public final static char TYPE = 'C';
        public final static char SUBTYPE = 'B';

        public final TypeField typeField = new TypeField(this, TYPE);
        public final SubtypeField subtypeField = new SubtypeField(this, SUBTYPE);

        public final CharsField myChars = new CharsField(this, 128);

        public final VarCharsField myVarChars = new VarCharsField(this, 1024);

        public final BytesField myBytes = new BytesField(this, 128);

        public final VarBytesField myVarBytes = new VarBytesField(this, 1024);


		// END_AUTO_GENERATED_CODE
	}
	
	@Test
	public void testCharsAndVarsFields() {
		
		Assert.assertTrue(true);
	}
}
