package com.coralblocks.coralproto.example;

import java.io.IOException;

import com.coralblocks.coralproto.AbstractProto;
import com.coralblocks.coralproto.IDL;
import com.coralblocks.coralproto.field.CharsField;
import com.coralblocks.coralproto.field.DoubleField;
import com.coralblocks.coralproto.field.GroupField;
import com.coralblocks.coralproto.field.IntField;
import com.coralblocks.coralproto.field.LongField;
import com.coralblocks.coralproto.field.ProtoField;
import com.coralblocks.coralproto.field.RepeatingGroupField;
import com.coralblocks.coralproto.field.SubtypeField;
import com.coralblocks.coralproto.field.TypeField;
import com.coralblocks.coralproto.field.VarCharsField;

public class PriceChangeMessage extends AbstractProto {
	
	private static final String TEXT = """
			
		  TYPE = P
		  SUBTYPE = C
		  
		  symbolId: long
		  symbolDesc: varchars(128)
		  mqReqId: long!
		  
		  bids:
		      levelId: long!
		      priceLevel: double
		      qty: int
		      legs:
		        legId: int
		        legDesc: chars(8)!
		      orders: int
		  
		  asks:
		      levelId: long!
		      priceLevel: double
		      qty: int
		      legs:
		        legId: int
		        legDesc: chars(8)!
		      orders: int
		  
		  lastTradeQty: long!
		  lastTradePrice: double!
			
	""";
	
	public static void main(String[] args) throws IOException {
		IDL idl = new IDL(TEXT);
		String filePath = "src/main/java/com/coralblocks/coralproto/example/" + PriceChangeMessage.class.getSimpleName() + ".java";
		String sourceCode = idl.getCode();
		IDL.replaceAutoGeneratedCode(filePath, sourceCode);
	}

	// Auto-generated code. Do not edit or change anything below here
	
	// BEGIN_AUTO_GENERATED_CODE

    public final static char TYPE = 'P';
    public final static char SUBTYPE = 'C';

    public final TypeField typeField = new TypeField(this, TYPE);
    public final SubtypeField subtypeField = new SubtypeField(this, SUBTYPE);

    public final LongField symbolId = new LongField(this);

    public final VarCharsField symbolDesc = new VarCharsField(this, 128);

    public final LongField mqReqId = new LongField(this, true);

    public static class BidsRepeatingGroup extends RepeatingGroupField {

        public LongField levelId;

        public DoubleField priceLevel;

        public IntField qty;

        public static class LegsRepeatingGroup extends RepeatingGroupField {

            public IntField legId;

            public CharsField legDesc;

            public LegsRepeatingGroup(AbstractProto proto) {
                this(proto, new IntField(), new CharsField(8, true));
            }

            public LegsRepeatingGroup(AbstractProto proto, ProtoField ... protoFields) {
                super(proto, protoFields);
            }

            @Override
            public GroupField nextElement() {
                GroupField groupField = super.nextElement();
                this.legId = (IntField) groupField.internalArray()[0];
                this.legDesc = (CharsField) groupField.internalArray()[1];
                return groupField;
            } 

            @Override
            public GroupField iterNext() {
                GroupField groupField = super.iterNext();
                if (groupField != null) {
                    this.legId = (IntField) groupField.internalArray()[0];
                    this.legDesc = (CharsField) groupField.internalArray()[1];
                }
                return groupField;
            } 

            @Override
            protected final RepeatingGroupField newInstance(ProtoField[] protoFields) {
                return new BidsRepeatingGroup.LegsRepeatingGroup(null, protoFields);
            } 

        }

        BidsRepeatingGroup.LegsRepeatingGroup legs;

        public IntField orders;

        public BidsRepeatingGroup(AbstractProto proto) {
            this(proto, new LongField(true), new DoubleField(), new IntField(), new BidsRepeatingGroup.LegsRepeatingGroup(null), new IntField());
        }

        public BidsRepeatingGroup(AbstractProto proto, ProtoField ... protoFields) {
            super(proto, protoFields);
        }

        @Override
        public GroupField nextElement() {
            GroupField groupField = super.nextElement();
            this.levelId = (LongField) groupField.internalArray()[0];
            this.priceLevel = (DoubleField) groupField.internalArray()[1];
            this.qty = (IntField) groupField.internalArray()[2];
            this.legs = (BidsRepeatingGroup.LegsRepeatingGroup) groupField.internalArray()[3];
            this.orders = (IntField) groupField.internalArray()[4];
            return groupField;
        } 

        @Override
        public GroupField iterNext() {
            GroupField groupField = super.iterNext();
            if (groupField != null) {
                this.levelId = (LongField) groupField.internalArray()[0];
                this.priceLevel = (DoubleField) groupField.internalArray()[1];
                this.qty = (IntField) groupField.internalArray()[2];
                this.legs = (BidsRepeatingGroup.LegsRepeatingGroup) groupField.internalArray()[3];
                this.orders = (IntField) groupField.internalArray()[4];
            }
            return groupField;
        } 

        @Override
        protected final RepeatingGroupField newInstance(ProtoField[] protoFields) {
            return new BidsRepeatingGroup(null, protoFields);
        } 

    }

    BidsRepeatingGroup bids = new BidsRepeatingGroup(this);

    public static class AsksRepeatingGroup extends RepeatingGroupField {

        public LongField levelId;

        public DoubleField priceLevel;

        public IntField qty;

        public static class LegsRepeatingGroup extends RepeatingGroupField {

            public IntField legId;

            public CharsField legDesc;

            public LegsRepeatingGroup(AbstractProto proto) {
                this(proto, new IntField(), new CharsField(8, true));
            }

            public LegsRepeatingGroup(AbstractProto proto, ProtoField ... protoFields) {
                super(proto, protoFields);
            }

            @Override
            public GroupField nextElement() {
                GroupField groupField = super.nextElement();
                this.legId = (IntField) groupField.internalArray()[0];
                this.legDesc = (CharsField) groupField.internalArray()[1];
                return groupField;
            } 

            @Override
            public GroupField iterNext() {
                GroupField groupField = super.iterNext();
                if (groupField != null) {
                    this.legId = (IntField) groupField.internalArray()[0];
                    this.legDesc = (CharsField) groupField.internalArray()[1];
                }
                return groupField;
            } 

            @Override
            protected final RepeatingGroupField newInstance(ProtoField[] protoFields) {
                return new AsksRepeatingGroup.LegsRepeatingGroup(null, protoFields);
            } 

        }

        AsksRepeatingGroup.LegsRepeatingGroup legs;

        public IntField orders;

        public AsksRepeatingGroup(AbstractProto proto) {
            this(proto, new LongField(true), new DoubleField(), new IntField(), new AsksRepeatingGroup.LegsRepeatingGroup(null), new IntField());
        }

        public AsksRepeatingGroup(AbstractProto proto, ProtoField ... protoFields) {
            super(proto, protoFields);
        }

        @Override
        public GroupField nextElement() {
            GroupField groupField = super.nextElement();
            this.levelId = (LongField) groupField.internalArray()[0];
            this.priceLevel = (DoubleField) groupField.internalArray()[1];
            this.qty = (IntField) groupField.internalArray()[2];
            this.legs = (AsksRepeatingGroup.LegsRepeatingGroup) groupField.internalArray()[3];
            this.orders = (IntField) groupField.internalArray()[4];
            return groupField;
        } 

        @Override
        public GroupField iterNext() {
            GroupField groupField = super.iterNext();
            if (groupField != null) {
                this.levelId = (LongField) groupField.internalArray()[0];
                this.priceLevel = (DoubleField) groupField.internalArray()[1];
                this.qty = (IntField) groupField.internalArray()[2];
                this.legs = (AsksRepeatingGroup.LegsRepeatingGroup) groupField.internalArray()[3];
                this.orders = (IntField) groupField.internalArray()[4];
            }
            return groupField;
        } 

        @Override
        protected final RepeatingGroupField newInstance(ProtoField[] protoFields) {
            return new AsksRepeatingGroup(null, protoFields);
        } 

    }

    AsksRepeatingGroup asks = new AsksRepeatingGroup(this);

    public final LongField lastTradeQty = new LongField(this, true);

    public final DoubleField lastTradePrice = new DoubleField(this, true);


	// END_AUTO_GENERATED_CODE

}
