package com.coralblocks.coralproto.example;

import java.io.IOException;

import com.coralblocks.coralproto.AbstractProto;
import com.coralblocks.coralproto.IDL;
import com.coralblocks.coralproto.field.LongField;
import com.coralblocks.coralproto.field.SubtypeField;
import com.coralblocks.coralproto.field.TypeField;
import com.coralblocks.coralproto.field.VarCharsField;

public class ProtoMessage1 extends AbstractProto {
	
	private static final String TEXT = """
			
			TYPE = P
			SUBTYPE = A
			
			symbolId: long
			symbolDesc: varchars(128)!
	""";
	
	public static void main(String[] args) throws IOException {
		IDL idl = new IDL(TEXT);
		String filePath = "src/main/java/com/coralblocks/coralproto/example/" + ProtoMessage1.class.getSimpleName() + ".java";
		String sourceCode = idl.getCode();
		IDL.replaceAutoGeneratedCode(filePath, sourceCode);
	}

	// Auto-generated code. Do not edit or change anything below here
	
	// BEGIN_AUTO_GENERATED_CODE

    public final static char TYPE = 'P';
    public final static char SUBTYPE = 'A';

    public final TypeField typeField = new TypeField(this, TYPE);
    public final SubtypeField subtypeField = new SubtypeField(this, SUBTYPE);

    public final LongField symbolId = new LongField(this);

    public final VarCharsField symbolDesc = new VarCharsField(this, 128, true);


	// END_AUTO_GENERATED_CODE

}
